networks:
  api-gestao-bancaria-network:
    name: api-gestao-bancaria-network
    driver: bridge

# Cria um volume nomeado
volumes:
  db-data:

services:
  apache-server-service:
    container_name: apache-server
    build:
      context: ./
      dockerfile: .docker/images/apache/Dockerfile
    ports:
      - 8999:80
    networks:
      - api-gestao-bancaria-network
    depends_on:
      - mysql-server-service
        # condition: service_healthy
    mem_limit: 128m
    mem_reservation: 64m
    cpus: 0.5

  mysql-server-service:
    container_name: mysql-server
    image: mysql
    expose: 
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=laravel
      - MYSQL_DATABASE=SISTEMA_GESTAO_BANCARIA
    networks:
      - api-gestao-bancaria-network
    volumes:
      - db-data:/var/lib/mysql
    mem_limit: 896m
    mem_reservation: 512m
    cpus: 0.5
    # healthcheck:
    #   test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 20
    